# Generated by Django 2.2 on 2021-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.CharField(max_length=250, unique=True)),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
